before_script:
  - apt update --yes
  - apt install --yes cmake
  - apt install --yes clang-tidy

build-gcc11:
  image: gcc:11
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    untracked: true

check:
  before_script: []
  image: ubuntu:20.04
  stage: .pre
  script:
    - apt update --yes
    - apt install --yes cppcheck
    - echo "Linting"
    - cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem missingInclude ./src/ ./libs/

test-gcc11:
  image: gcc:11
  stage: test
  needs: ["build-gcc11"]
  script:
    - echo "Testing"
    - cd build
    - make test
  artifacts:
    untracked: true
